### ISSUE TITLE
Untight constraints between Domain entities and Infrastructure configurations

### ISSUE THREAD

**Issue by kaitoz11** [ProFile-org/ProFile-BE#58]
https://github.com/ProFile-org/ProFile-BE/blob/cf8d2789c238de91a040d7b4be5c62f88b2cdae9/src/Infrastructure/Persistence/Configurations/RoomConfiguration.cs#L17-L18

https://github.com/ProFile-org/ProFile-BE/blob/cf8d2789c238de91a040d7b4be5c62f88b2cdae9/src/Domain/Entities/Physical/Room.cs#L8

---
## Suggestion:
```C#
public string? Description { get; set; } 
```

**Comment by ChienNQuang** [comment]
approve, raise a PR
